Homework3: Alexander Shvedov
belovmd/it-academy-spring-2021 pull request #42
Opened 2021-03-20 18:55 UTC by alexshvedov1997

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-04-25 22:39 UTC, belovmd requested changes
sanity checks failed - no task description

2021-04-25 22:39 UTC, belovmd commented on src/homework3/task1.py
> +    if not elem % 3 and not elem % 5:
15?

2021-04-25 22:39 UTC, belovmd commented on src/homework3/task2.py
> +lst_2 = [str(chr1) + chr2 for chr1 in range(1, 5) for chr2 in "a"]
'1234'

2021-04-25 22:39 UTC, belovmd commented on src/homework3/task2.py
> +lst_2 = [str(chr1) + chr2 for chr1 in range(1, 5) for chr2 in "a"]
+'a'

2021-04-25 22:39 UTC, belovmd commented on src/homework3/task3.py
> +print("set: {} type: {}".format(set_1, type(set_1)))
redundant print

2021-04-25 22:39 UTC, belovmd commented on src/homework3/task4.py
> +    while count_num:
has O(1) solution

2021-04-27 18:46 UTC, alexshvedov1997 commented on src/homework3/task4.py
> +    while count_num:
Я оптимизировал код, но не знаю как еще улучшить код для списка произвольных чисел.

2021-04-27 18:58 UTC, alexshvedov1997 commented on src/homework3/task1.py
> +    if not elem % 3 and not elem % 5:
I don't understand what's wrong with the programm.

2021-06-07 21:35 UTC, belovmd approved these changes
7,5

2021-06-07 21:35 UTC, belovmd commented on src/homework3/task1.py
> +    if not elem % 3 and not elem % 5:
`if not element %15:`

review not addressed

2021-06-07 21:35 UTC, belovmd commented on src/homework3/task2.py
> +lst_2 = [str(chr1) + 'a' for chr1 in range(1, 5)]
chr1 in '1234' review not addressed

2021-06-07 21:35 UTC, belovmd commented on src/homework3/task3.py
> +print("set: {}".format(set_1))
redundant print. review not addressed

2021-06-07 21:35 UTC, belovmd commented on src/homework3/task3.py
> +List practice
Task description contradicts solution. (it's description from task2)

2021-06-07 21:35 UTC, belovmd commented on src/homework3/task4.py
> +def calculate_count_of_pairs(lst_):
here we have arithmetical progression. number of pairs - n(n-1)/2

2021-06-07 21:35 UTC, closed without merging