Homework2: Natalia Mashliakevich
belovmd/it-academy-spring-2021 pull request #49
Opened 2021-03-23 15:12 UTC by nataliasipenko

- [ ] ### PR checklist

Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-04-25 19:18 UTC, belovmd requested changes
- Sanity checks failed - redundant files in PR
- it would be nice to have one 5 kyu task for higher score
- please address next issues:

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task1.py
> +# Подсчет общей цены в рублях и копейках за L товаров
redundant comments

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task1.py
> +print('Общая цена за', S, 'шт. составляет', M, 'рублей(-я)', N, 'копеек')
i don't understand this pring

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task2.py
> +punctuation = ['(', ')', '?', ':', ';', ',', '.', '!', '/', '"', "'"]
what about > { and many others?

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task5.py
> +    fibonacci_sum = fibonacci_num_1 + fibonacci_num_2
a, b = a+b, a

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task6.py
> +    print('С однозначным числом операция не выполняется')
all 1-digit numbers are palindrom

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task7.py
> +    perimeter = float((a + b + c) / 2)
it's semi-perimeter

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task7.py
> +    perimeter = float((a + b + c) / 2)
redundant `float()`

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +        if every == 25:
person in people

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +            if d25 >= 1:
if d25?

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +            if d50 >= 1 and d25 >= 1:
if d50?

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +    return template.format(*n)
nice

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +            if summa > 9:
same code as above. why couldn't we do it in one while?

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +        print(0)
return 0

2021-04-25 19:18 UTC, belovmd commented on src/homework2/task8.py
> +# Короткое решение:
please chose one solution

2021-05-03 16:49 UTC, nataliasipenko commented on src/homework2/task1.py
> +print('Общая цена за', S, 'шт. составляет', M, 'рублей(-я)', N, 'копеек')
_Напишите программу, которая считает общую цену. Вводится **M** рублей и **N** копеек цена, а также количество **S** товара. Посчитайте общую цену в рублях и копейках за **L** товаров._ We have some amount of goods (S) and final price of this quantity.  Firstly we should find price for one item (price for all items ((m*100) + n) / s). Then we get another quantity of goods (L) and should find out, how much is this quantity (L) of goods.

2021-05-03 17:03 UTC, nataliasipenko reviewed
Changes made. Review requested (please see my comment below).

2021-06-16 14:25 UTC, belovmd approved these changes
8,5

2021-06-16 14:25 UTC, belovmd commented on src/homework2/task1.py
> +print('Общая цена за', S, 'шт. составляет', M, 'рублей(-я)', N, 'копеек')
yes but this print goes before calculation

2021-06-16 14:25 UTC, belovmd commented on src/homework2/task7.py
> +    perimeter = (a + b + c)
it should be a semi-perimeter. 
it gives wrong answer

2021-06-16 14:26 UTC, closed without merging