Homework3: Natalia Mashliakevich
belovmd/it-academy-spring-2021 pull request #68
Opened 2021-04-06 21:52 UTC by nataliasipenko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-04-29 21:14 UTC, belovmd requested changes
- sanity checks failed - redundant code in PR

2021-04-29 21:14 UTC, belovmd commented on src/homework3/task1.py
> +    if number % 3 == 0 and number % 5 == 0:
15?

2021-04-29 21:14 UTC, belovmd commented on src/homework3/task1.py
> +    if number % 3 == 0 and number % 5 == 0:
`not smth` instead of `smth == 0`

2021-04-29 21:14 UTC, belovmd commented on src/homework3/task2.py
> +task3 = [c + d for c in "1234" for d in "a"]
+ 'a'

2021-04-29 21:14 UTC, belovmd commented on src/homework3/task4.py
> +    for j in range(i + 1, len(str2)):
can be solved with O(n)

2021-04-29 21:14 UTC, belovmd commented on src/homework3/task6.py
> +# Через while-loop
please choose one.

2021-05-03 18:08 UTC, nataliasipenko reviewed
Changes made. Review requested. 
Thank you in advance!

2021-06-16 14:30 UTC, belovmd approved these changes
8

2021-06-16 14:30 UTC, belovmd commented on src/homework3/task2.py
> +print(task3.pop(1))  # task4
redundant comment

2021-06-16 14:30 UTC, belovmd commented on src/homework3/task2.py
> +task3 = [c + d for c in '1234' for d in 'a']
c + 'a'

2021-06-16 14:30 UTC, closed without merging