Homework4: Natalia Mashliakevich
belovmd/it-academy-spring-2021 pull request #77
Opened 2021-04-16 19:08 UTC by nataliasipenko

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-05-10 21:08 UTC, belovmd requested changes
sanity checks failed - redundant files in pr

2021-06-01 14:25 UTC, nataliasipenko commented
> sanity checks failed - redundant files in pr

amended

2021-06-16 14:34 UTC, belovmd approved these changes
6,5

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task2.py
> +# str1 = 'Russia Moscow Petersburg Novgorod Kaluga'
redundant comments

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task2.py
> +        key, value = lst[0], lst[1:]
country, *cities = str_.split()

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task2.py
> +        dct[key] = value
not optimal data structure

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task3.py
> +print(len(set(lst1) ^ set(lst2)))
task not solved it's intersection

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task4.py
> +print(len(set(lst1) - set(lst2)))
not solved it's symmetric difference

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task3.py
> +# Поскольку в условии указано различных чисел (т.е. не одинаковых),
redundant comments

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task5.py
> +# Входные данные
inconsistent docstring - with """ at the beginning and # in the end. inaccurate.

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task5.py
> +# print(dct)
redundant comments

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task6.py
> +print(set(str_.split()))
why do we need this print?

2021-06-16 14:34 UTC, belovmd commented on src/homework4/task7.py
> +print(max(a, b))
it's a cheat - you don't know where is result and use max

2021-06-16 14:35 UTC, closed without merging